/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Sat Jan  9 22:36:47 2021
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 2018
#define M_7 100
#define M_11 1
#define M_12 15
#define M_16 1
#define M_17 15
#define M_28 3
#define M_34 1
#define M_35 15
#define M_37 1
#define M_38 15
#define M_48 600
#define M_49 15
#define M_50 15
#define M_51 15
#define M_52 15
#define M_53 2000

// center of mass
#define L_1_6 -1.26
#define L_3_6 0.6
#define L_1_48 -4.581
#define L_3_48 0.054

// inertia
#define IN_1_6 895.67
#define IN_5_6 4218.04
#define IN_9_6 4587.72
#define IN_1_12 0.1
#define IN_5_12 0.8
#define IN_9_12 0.1
#define IN_1_17 0.1
#define IN_5_17 0.8
#define IN_9_17 0.1
#define IN_1_35 0.1
#define IN_5_35 0.8
#define IN_9_35 0.1
#define IN_1_38 0.1
#define IN_5_38 0.8
#define IN_9_38 0.1
#define IN_1_48 384.9
#define IN_5_48 3033.6
#define IN_9_48 3373.6
#define IN_1_49 0.1
#define IN_5_49 0.8
#define IN_9_49 0.1
#define IN_1_50 0.1
#define IN_5_50 0.8
#define IN_9_50 0.1
#define IN_1_51 0.1
#define IN_5_51 0.8
#define IN_9_51 0.1
#define IN_1_52 0.1
#define IN_5_52 0.8
#define IN_9_52 0.1
#define IN_1_53 4716
#define IN_5_53 13406
#define IN_9_53 12207

// body point
#define DPT_1_1 -0.02
#define DPT_2_1 -0.41
#define DPT_3_1 0.2
#define DPT_1_2 -0.02
#define DPT_2_2 0.41
#define DPT_3_2 0.2
#define DPT_2_3 0.41
#define DPT_2_4 -0.41
#define DPT_1_5 -2.89
#define DPT_2_5 -0.41
#define DPT_1_6 -2.89
#define DPT_2_6 -0.41
#define DPT_3_6 0.3
#define DPT_1_7 -2.89
#define DPT_2_7 0.41
#define DPT_1_8 -0.2
#define DPT_3_8 -0.05
#define DPT_1_9 -0.2
#define DPT_3_9 0.1
#define DPT_1_10 -2.89
#define DPT_2_10 0.41
#define DPT_3_10 0.3
#define DPT_2_11 0.41
#define DPT_3_11 0.3
#define DPT_1_12 -2.89
#define DPT_2_12 0.41
#define DPT_3_12 0.2
#define DPT_1_13 -2.89
#define DPT_2_13 -0.41
#define DPT_3_13 0.2
#define DPT_2_14 -0.41
#define DPT_3_14 0.3
#define DPT_1_15 -3.18
#define DPT_3_15 -0.05
#define DPT_1_16 -1.26
#define DPT_3_16 0.6
#define DPT_1_17 -4.2
#define DPT_3_17 0.2
#define DPT_2_18 -0.4
#define DPT_1_19 0.1
#define DPT_2_19 -0.2
#define DPT_1_20 -0.1
#define DPT_3_20 -0.1
#define DPT_1_21 0.02
#define DPT_3_21 -0.2
#define DPT_3_22 -0.1
#define DPT_2_24 0.4
#define DPT_1_25 0.1
#define DPT_2_25 0.2
#define DPT_1_26 0.02
#define DPT_3_26 -0.2
#define DPT_3_27 -0.1
#define DPT_1_28 -0.1
#define DPT_3_28 -0.1
#define DPT_2_30 0.4
#define DPT_2_31 0.3
#define DPT_2_32 -0.4
#define DPT_2_33 -0.3
#define DPT_2_34 -0.4
#define DPT_2_35 -0.3
#define DPT_2_36 0.4
#define DPT_2_37 0.3
#define DPT_1_38 0.3
#define DPT_2_38 0.61
#define DPT_3_40 0.25
#define DPT_1_41 0.3
#define DPT_2_41 -0.61
#define DPT_3_42 0.25
#define DPT_2_43 -0.26
#define DPT_2_44 0.26
#define DPT_1_45 0.1
#define DPT_2_45 -0.54
#define DPT_1_46 0.1
#define DPT_2_46 0.54
#define DPT_2_47 0.4
#define DPT_1_48 0.1
#define DPT_2_48 0.2
#define DPT_3_49 -0.2
#define DPT_3_50 -0.1
#define DPT_2_52 -0.4
#define DPT_1_53 0.1
#define DPT_2_53 -0.2
#define DPT_3_54 -0.1
#define DPT_3_55 -0.2
#define DPT_1_58 0.3
#define DPT_2_58 0.61
#define DPT_1_59 0.3
#define DPT_2_59 -0.61
#define DPT_3_60 0.25
#define DPT_3_61 0.25
#define DPT_1_62 -4.559
#define DPT_2_62 -1.12
#define DPT_3_62 -0.1875
#define DPT_1_63 -4.559
#define DPT_2_63 1.12
#define DPT_3_63 -0.1875
#define DPT_1_64 -5.359
#define DPT_2_64 1.12
#define DPT_3_64 -0.1875
#define DPT_1_65 -5.359
#define DPT_2_65 -1.12
#define DPT_3_65 -0.1875
#define DPT_1_66 -4.38
#define DPT_3_66 0.17
#define DPT_1_67 -4.581
#define DPT_3_67 0.054

// ============================================================ //

# endif
