/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue May 18 15:39:38 2021
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 2018
#define M_7 100
#define M_11 1
#define M_12 15
#define M_16 1
#define M_17 15
#define M_28 3
#define M_34 0.5
#define M_36 1
#define M_37 15
#define M_39 1
#define M_40 15
#define M_50 1.5
#define M_54 600
#define M_55 15
#define M_56 15
#define M_57 15
#define M_58 15
#define M_59 2000

// center of mass
#define L_1_6 -1.26
#define L_3_6 0.6
#define L_1_54 -4.581
#define L_3_54 0.054

// inertia
#define IN_1_6 895.67
#define IN_5_6 4218.04
#define IN_9_6 4587.72
#define IN_1_12 0.1
#define IN_5_12 0.8
#define IN_9_12 0.1
#define IN_1_17 0.1
#define IN_5_17 0.8
#define IN_9_17 0.1
#define IN_1_34 0.0001
#define IN_5_34 0.0001
#define IN_9_34 0.0001
#define IN_1_37 0.1
#define IN_5_37 0.8
#define IN_9_37 0.1
#define IN_1_40 0.1
#define IN_5_40 0.8
#define IN_9_40 0.1
#define IN_1_50 0.014
#define IN_5_50 0.014
#define IN_9_50 0.027
#define IN_1_54 384.9
#define IN_5_54 3033.6
#define IN_9_54 3373.6
#define IN_1_55 0.1
#define IN_5_55 0.8
#define IN_9_55 0.1
#define IN_1_56 0.1
#define IN_5_56 0.8
#define IN_9_56 0.1
#define IN_1_57 0.1
#define IN_5_57 0.8
#define IN_9_57 0.1
#define IN_1_58 0.1
#define IN_5_58 0.8
#define IN_9_58 0.1
#define IN_1_59 4716
#define IN_5_59 13406
#define IN_9_59 12207

// body point
#define DPT_1_1 -0.02
#define DPT_2_1 -0.41
#define DPT_3_1 0.2
#define DPT_1_2 -0.02
#define DPT_2_2 0.41
#define DPT_3_2 0.2
#define DPT_2_3 0.41
#define DPT_2_4 -0.41
#define DPT_1_5 -2.89
#define DPT_2_5 -0.41
#define DPT_1_6 -2.89
#define DPT_2_6 -0.41
#define DPT_3_6 0.3
#define DPT_1_7 -2.89
#define DPT_2_7 0.41
#define DPT_1_8 -0.2
#define DPT_3_8 -0.05
#define DPT_1_9 -0.2
#define DPT_3_9 0.1
#define DPT_1_10 -2.89
#define DPT_2_10 0.41
#define DPT_3_10 0.3
#define DPT_2_11 0.41
#define DPT_3_11 0.3
#define DPT_1_12 -2.89
#define DPT_2_12 0.41
#define DPT_3_12 0.2
#define DPT_1_13 -2.89
#define DPT_2_13 -0.41
#define DPT_3_13 0.2
#define DPT_2_14 -0.41
#define DPT_3_14 0.3
#define DPT_1_15 -3.18
#define DPT_3_15 -0.05
#define DPT_1_16 -1.36
#define DPT_3_16 0.35
#define DPT_1_17 -1
#define DPT_2_17 0.23
#define DPT_3_17 0.55
#define DPT_1_18 -4.2
#define DPT_3_18 0.2
#define DPT_2_19 -0.4
#define DPT_1_20 0.1
#define DPT_2_20 -0.2
#define DPT_1_21 -0.1
#define DPT_3_21 -0.1
#define DPT_1_22 0.02
#define DPT_3_22 -0.2
#define DPT_3_23 -0.1
#define DPT_2_26 0.4
#define DPT_1_27 0.1
#define DPT_2_27 0.2
#define DPT_1_28 0.02
#define DPT_3_28 -0.2
#define DPT_3_29 -0.1
#define DPT_1_30 -0.1
#define DPT_3_30 -0.1
#define DPT_2_32 0.4
#define DPT_2_33 0.3
#define DPT_2_34 -0.4
#define DPT_2_35 -0.3
#define DPT_2_36 -0.4
#define DPT_2_37 -0.3
#define DPT_2_38 0.4
#define DPT_2_39 0.3
#define DPT_1_40 0.3
#define DPT_2_40 0.55
#define DPT_3_42 0.25
#define DPT_1_43 0.3
#define DPT_2_43 -0.55
#define DPT_3_44 0.25
#define DPT_2_45 -0.26
#define DPT_2_46 0.26
#define DPT_2_47 0.23
#define DPT_1_48 0.1
#define DPT_2_48 -0.54
#define DPT_1_49 0.1
#define DPT_2_49 0.54
#define DPT_2_50 0.4
#define DPT_1_51 0.1
#define DPT_2_51 0.2
#define DPT_3_52 -0.2
#define DPT_3_53 -0.1
#define DPT_2_55 -0.4
#define DPT_1_56 0.1
#define DPT_2_56 -0.2
#define DPT_3_57 -0.1
#define DPT_3_58 -0.2
#define DPT_1_61 0.3
#define DPT_2_61 0.55
#define DPT_1_62 0.3
#define DPT_2_62 -0.55
#define DPT_3_63 0.25
#define DPT_3_64 0.25
#define DPT_1_65 -4.559
#define DPT_2_65 -1.12
#define DPT_3_65 -0.1875
#define DPT_1_66 -4.559
#define DPT_2_66 1.12
#define DPT_3_66 -0.1875
#define DPT_1_67 -5.359
#define DPT_2_67 1.12
#define DPT_3_67 -0.1875
#define DPT_1_68 -5.359
#define DPT_2_68 -1.12
#define DPT_3_68 -0.1875
#define DPT_1_69 -4.38
#define DPT_3_69 0.17

// ============================================================ //

# endif
