/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Wed May 12 14:44:06 2021
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 2018
#define M_7 100
#define M_11 1
#define M_12 15
#define M_16 1
#define M_17 15
#define M_28 3
#define M_34 0.5
#define M_36 1
#define M_37 15
#define M_39 1
#define M_40 15
#define M_50 600
#define M_51 15
#define M_52 15
#define M_53 15
#define M_54 15
#define M_55 2000
#define M_59 1.5

// center of mass
#define L_1_6 -1.26
#define L_3_6 0.6
#define L_1_50 -4.581
#define L_3_50 0.054

// inertia
#define IN_1_6 895.67
#define IN_5_6 4218.04
#define IN_9_6 4587.72
#define IN_1_12 0.1
#define IN_5_12 0.8
#define IN_9_12 0.1
#define IN_1_17 0.1
#define IN_5_17 0.8
#define IN_9_17 0.1
#define IN_1_34 0.0001
#define IN_5_34 0.0001
#define IN_9_34 0.0001
#define IN_1_37 0.1
#define IN_5_37 0.8
#define IN_9_37 0.1
#define IN_1_40 0.1
#define IN_5_40 0.8
#define IN_9_40 0.1
#define IN_1_50 384.9
#define IN_5_50 3033.6
#define IN_9_50 3373.6
#define IN_1_51 0.1
#define IN_5_51 0.8
#define IN_9_51 0.1
#define IN_1_52 0.1
#define IN_5_52 0.8
#define IN_9_52 0.1
#define IN_1_53 0.1
#define IN_5_53 0.8
#define IN_9_53 0.1
#define IN_1_54 0.1
#define IN_5_54 0.8
#define IN_9_54 0.1
#define IN_1_55 4716
#define IN_5_55 13406
#define IN_9_55 12207
#define IN_1_59 0.014
#define IN_5_59 0.014
#define IN_9_59 0.027

// body point
#define DPT_1_1 -0.02
#define DPT_2_1 -0.41
#define DPT_3_1 0.2
#define DPT_1_2 -0.02
#define DPT_2_2 0.41
#define DPT_3_2 0.2
#define DPT_2_3 0.41
#define DPT_2_4 -0.41
#define DPT_1_5 -2.89
#define DPT_2_5 -0.41
#define DPT_1_6 -2.89
#define DPT_2_6 -0.41
#define DPT_3_6 0.3
#define DPT_1_7 -2.89
#define DPT_2_7 0.41
#define DPT_1_8 -0.2
#define DPT_3_8 -0.05
#define DPT_1_9 -0.2
#define DPT_3_9 0.1
#define DPT_1_10 -2.89
#define DPT_2_10 0.41
#define DPT_3_10 0.3
#define DPT_2_11 0.41
#define DPT_3_11 0.3
#define DPT_1_12 -2.89
#define DPT_2_12 0.41
#define DPT_3_12 0.2
#define DPT_1_13 -2.89
#define DPT_2_13 -0.41
#define DPT_3_13 0.2
#define DPT_2_14 -0.41
#define DPT_3_14 0.3
#define DPT_1_15 -3.18
#define DPT_3_15 -0.05
#define DPT_1_16 -1.26
#define DPT_3_16 0.6
#define DPT_1_17 -4.2
#define DPT_3_17 0.2
#define DPT_1_18 -1
#define DPT_2_18 0.23
#define DPT_3_18 0.55
#define DPT_2_19 -0.4
#define DPT_1_20 0.1
#define DPT_2_20 -0.2
#define DPT_1_21 -0.1
#define DPT_3_21 -0.1
#define DPT_1_22 0.02
#define DPT_3_22 -0.2
#define DPT_3_23 -0.1
#define DPT_2_25 0.4
#define DPT_1_26 0.1
#define DPT_2_26 0.2
#define DPT_1_27 0.02
#define DPT_3_27 -0.2
#define DPT_3_28 -0.1
#define DPT_1_29 -0.1
#define DPT_3_29 -0.1
#define DPT_2_31 0.4
#define DPT_2_32 0.3
#define DPT_2_33 -0.4
#define DPT_2_34 -0.3
#define DPT_2_35 -0.4
#define DPT_2_36 -0.3
#define DPT_2_37 0.4
#define DPT_2_38 0.3
#define DPT_1_39 0.3
#define DPT_2_39 0.61
#define DPT_3_41 0.25
#define DPT_1_42 0.3
#define DPT_2_42 -0.61
#define DPT_3_43 0.25
#define DPT_2_44 -0.26
#define DPT_2_45 0.26
#define DPT_2_46 0.23
#define DPT_1_47 0.1
#define DPT_2_47 -0.54
#define DPT_1_48 0.1
#define DPT_2_48 0.54
#define DPT_2_49 0.4
#define DPT_1_50 0.1
#define DPT_2_50 0.2
#define DPT_3_51 -0.2
#define DPT_3_52 -0.1
#define DPT_2_54 -0.4
#define DPT_1_55 0.1
#define DPT_2_55 -0.2
#define DPT_3_56 -0.1
#define DPT_3_57 -0.2
#define DPT_1_60 0.3
#define DPT_2_60 0.61
#define DPT_1_61 0.3
#define DPT_2_61 -0.61
#define DPT_3_62 0.25
#define DPT_3_63 0.25
#define DPT_1_64 -4.559
#define DPT_2_64 -1.12
#define DPT_3_64 -0.1875
#define DPT_1_65 -4.559
#define DPT_2_65 1.12
#define DPT_3_65 -0.1875
#define DPT_1_66 -5.359
#define DPT_2_66 1.12
#define DPT_3_66 -0.1875
#define DPT_1_67 -5.359
#define DPT_2_67 -1.12
#define DPT_3_67 -0.1875
#define DPT_1_68 -4.38
#define DPT_3_68 0.17
#define DPT_1_69 -4.581
#define DPT_3_69 0.054

// ============================================================ //

# endif
